### ISSUE TITLE
Errors on vagrant up with Windows

### ISSUE THREAD

**Issue by zcwilt** [zencart/habitat#1]
cp: cannot create symbolic link ???/home/vagrant/habitat/tools/composer/vendor/bin/phpmod???: protocol error 

This is due to the fact that composer symlinks items in the vendor/bin directory 
e.g. 
phpunit -> ../phpunit/phpunit/phpunit
can probably work around for now, by not accessing vendor/bin but using full paths.

**Comment by drbyte** [comment]
> This is due to the fact that composer symlinks items in the vendor/bin directory 

Exactly.  And Laravel Homestead has the same problem: If you run `laravel new project`, it basically just unzips a set of files, and does NOT set permissions, and does NOT symlink to the correct files.

`vendor/bin/phpunit` is supposed to be a symlink to `vendor/phpunit/phpunit/phpunit` which is the real executable. The logic for detecting the working directories is broken because it's expecting that it's running from the symlink in `vendor/phpunit/phpunit/phpunit`.

The simplest solution I found was to:
- look at the files in `vendor/bin` and delete all those files and the corresponding `/vendor/xyz` directories for those same files
- then run composer install to rebuild the symlinks

... or just not use `laravel new project`, and instead just do a proper git checkout and let composer do its thing.

In the case of the Windows setup you posted this for, I suspect you'll need to do a global composer install to get those features to work properly on the host. 

Granted, you reported this issue a year ago and there have been numerous updates to Habitat in the meantime ... ;)
